$(function(){
	var currentIndex=0;
	var nextIndex=1;
	var timer;
	timer=setInterval(function(){
		$(".a").eq(currentIndex).fadeOut(1000);
		$(".a").eq(nextIndex).fadeIn(1000);
		$("span").eq(currentIndex).removeClass("current");
		$("span").eq(nextIndex).addClass("current");
		currentIndex=nextIndex;
		nextIndex++;
		if(nextIndex>4){
			nextIndex=0;
		}
	    },3000)
		$("#box").mouseover(function(){
			clearInterval(timer)
		})
		$("#box").mouseleave(function(){
			timer=setInterval(function(){
			$(".a").eq(currentIndex).fadeOut(1000);
			$(".a").eq(nextIndex).fadeIn(1000);
			$("span").eq(currentIndex).removeClass("current");
			$("span").eq(nextIndex).addClass("current");
			currentIndex=nextIndex;
			nextIndex++;
			if(nextIndex>4){
				nextIndex=0;
			}
			},3000)
			})
		$("#right").click(function(){
		$(".a").eq(currentIndex).fadeOut(1000);
		$(".a").eq(nextIndex).fadeIn(1000);
		$("span").eq(currentIndex).removeClass("current");
		$("span").eq(nextIndex).addClass("current");
			    currentIndex=nextIndex;
			    nextIndex++;
			    if(nextIndex>4){
						nextIndex=0;
					}
			})
			$("#left").click(function(){
				nextIndex=currentIndex-1;
				if(nextIndex<0){
					nextIndex=4
				}
				$(".a").eq(currentIndex).fadeOut(1000);
			    $(".a").eq(nextIndex).fadeIn(1000);
			    $("span").eq(currentIndex).removeClass("current");
			    $("span").eq(nextIndex).addClass("current");
			    currentIndex=nextIndex;
			    nextIndex++;
			    if(nextIndex>4){
						nextIndex=0;
					}
			})
			$("span").mouseover(function(){
//				console.log($(this).index())
                nextIndex=$(this).index();
                $(".a").eq(currentIndex).fadeOut(1000);
			    $(".a").eq(nextIndex).fadeIn(1000);
			    $("span").eq(currentIndex).removeClass("current");
			    $("span").eq(nextIndex).addClass("current");
			    currentIndex=nextIndex;
			    nextIndex++;
			    if(nextIndex>4){
						nextIndex=0;
					}
			})
})